name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/johanneslipp/mywebapp:latest
            ghcr.io/johanneslipp/mywebapp:v0.1

#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to GitHub Docker Registry
#        uses: docker/login-action@v1
#        with:
#          registry: docker.pkg.github.com
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push container image
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: docker.pkg.github.com/${{ github.repository }}/myapp:latest
